name: auction_clean_architecture
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.3
  bloc: ^8.0.3
  build_runner: ^2.2.0
  cloud_firestore: ^4.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  date_format: ^2.0.6
  date_time_picker: ^2.1.0
  equatable: ^2.0.3
  firebase_auth: ^4.1.5
  firebase_core: ^2.3.0
  firebase_database: ^10.0.6
  firebase_storage: ^11.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_datetime_picker: ^1.5.1
  flutter_facebook_auth: ^5.0.6
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.14
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.2.1
  form_validation: ^2.1.0+11
  form_validator: ^1.0.2
  get_it: ^7.2.0
  google_sign_in: ^5.4.2
  http: ^0.13.5
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  timeago: ^3.3.0
  timer_count_down: ^2.2.1
  uuid: ^3.0.6
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  android: true
  ios: false
  web: false

  color: "#06655C"

  #color_dark: "#042a49"
  # background_image: "assets/images/background.png"
  # image: assets/images/scout-1.png
  #branding_dark: assets/dart_dark.png

flutter_icons:
  android: true
  ios: true
  image_path: "asset/image/dd.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  color: "#FF655C"

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/image/
  # example:
  # fonts:  asset/image/mazadat_1.png'
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
